<?php
//Global Define 

$defineStatus[id] = array( '0','1','2','3','4');
$defineStatus[status_th] = array( 'ขายสินค้า','เติมสินค้า','คืนสินค้า','รีเซ็ตยอดเงิน','เติมเงินมือถือ'); 

$fetchProvince = [
	['id' => '1', 'jqvmap' => 'th-10', 'name_th' => 'กรุงเทพมหานคร', 'name_en' => 'Bangkok', 'geography_id' => '2'],
	['id' => '2', 'jqvmap' => 'th-11', 'name_th' => 'สมุทรปราการ', 'name_en' => 'Samut Prakan', 'geography_id' => '2'],
	['id' => '3', 'jqvmap' => 'th-12', 'name_th' => 'นนทบุรี', 'name_en' => 'Nonthaburi', 'geography_id' => '2'],
	['id' => '4', 'jqvmap' => 'th-13', 'name_th' => 'ปทุมธานี', 'name_en' => 'Pathum Thani', 'geography_id' => '2'],
	['id' => '5', 'jqvmap' => 'th-14', 'name_th' => 'พระนครศรีอยุธยา', 'name_en' => 'Phra Nakhon Si Ayutthaya', 'geography_id' => '2'],
	['id' => '6', 'jqvmap' => 'th-15', 'name_th' => 'อ่างทอง', 'name_en' => 'Ang Thong', 'geography_id' => '2'],
	['id' => '7', 'jqvmap' => 'th-16', 'name_th' => 'ลพบุรี', 'name_en' => 'Loburi', 'geography_id' => '2'],
	['id' => '8', 'jqvmap' => 'th-17', 'name_th' => 'สิงห์บุรี', 'name_en' => 'Sing Buri', 'geography_id' => '2'],
	['id' => '9', 'jqvmap' => 'th-18', 'name_th' => 'ชัยนาท', 'name_en' => 'Chai Nat', 'geography_id' => '2'],
	['id' => '10', 'jqvmap' => 'th-19', 'name_th' => 'สระบุรี', 'name_en' => 'Saraburi', 'geography_id' => '2'],
	['id' => '11', 'jqvmap' => 'th-20', 'name_th' => 'ชลบุรี', 'name_en' => 'Chon Buri', 'geography_id' => '5'],
	['id' => '12', 'jqvmap' => 'th-21', 'name_th' => 'ระยอง', 'name_en' => 'Rayong', 'geography_id' => '5'],
	['id' => '13', 'jqvmap' => 'th-22', 'name_th' => 'จันทบุรี', 'name_en' => 'Chanthaburi', 'geography_id' => '5'],
	['id' => '14', 'jqvmap' => 'th-23', 'name_th' => 'ตราด', 'name_en' => 'Trat', 'geography_id' => '5'],
	['id' => '15', 'jqvmap' => 'th-24', 'name_th' => 'ฉะเชิงเทรา', 'name_en' => 'Chachoengsao', 'geography_id' => '5'],
	['id' => '16', 'jqvmap' => 'th-25', 'name_th' => 'ปราจีนบุรี', 'name_en' => 'Prachin Buri', 'geography_id' => '5'],
	['id' => '17', 'jqvmap' => 'th-26', 'name_th' => 'นครนายก', 'name_en' => 'Nakhon Nayok', 'geography_id' => '2'],
	['id' => '18', 'jqvmap' => 'th-27', 'name_th' => 'สระแก้ว', 'name_en' => 'Sa Kaeo', 'geography_id' => '5'],
	['id' => '19', 'jqvmap' => 'th-30', 'name_th' => 'นครราชสีมา', 'name_en' => 'Nakhon Ratchasima', 'geography_id' => '3'],
	['id' => '20', 'jqvmap' => 'th-31', 'name_th' => 'บุรีรัมย์', 'name_en' => 'Buri Ram', 'geography_id' => '3'],
	['id' => '21', 'jqvmap' => 'th-32', 'name_th' => 'สุรินทร์', 'name_en' => 'Surin', 'geography_id' => '3'],
	['id' => '22', 'jqvmap' => 'th-33', 'name_th' => 'ศรีสะเกษ', 'name_en' => 'Si Sa Ket', 'geography_id' => '3'],
	['id' => '23', 'jqvmap' => 'th-34', 'name_th' => 'อุบลราชธานี', 'name_en' => 'Ubon Ratchathani', 'geography_id' => '3'],
	['id' => '24', 'jqvmap' => 'th-35', 'name_th' => 'ยโสธร', 'name_en' => 'Yasothon', 'geography_id' => '3'],
	['id' => '25', 'jqvmap' => 'th-36', 'name_th' => 'ชัยภูมิ', 'name_en' => 'Chaiyaphum', 'geography_id' => '3'],
	['id' => '26', 'jqvmap' => 'th-37', 'name_th' => 'อำนาจเจริญ', 'name_en' => 'Amnat Charoen', 'geography_id' => '3'],
	['id' => '27', 'jqvmap' => 'th-39', 'name_th' => 'หนองบัวลำภู', 'name_en' => 'Nong Bua Lam Phu', 'geography_id' => '3'],
	['id' => '28', 'jqvmap' => 'th-40', 'name_th' => 'ขอนแก่น', 'name_en' => 'Khon Kaen', 'geography_id' => '3'],
	['id' => '29', 'jqvmap' => 'th-41', 'name_th' => 'อุดรธานี', 'name_en' => 'Udon Thani', 'geography_id' => '3'],
	['id' => '30', 'jqvmap' => 'th-42', 'name_th' => 'เลย', 'name_en' => 'Loei', 'geography_id' => '3'],
	['id' => '31', 'jqvmap' => 'th-43', 'name_th' => 'หนองคาย', 'name_en' => 'Nong Khai', 'geography_id' => '3'],
	['id' => '32', 'jqvmap' => 'th-44', 'name_th' => 'มหาสารคาม', 'name_en' => 'Maha Sarakham', 'geography_id' => '3'],
	['id' => '33', 'jqvmap' => 'th-45', 'name_th' => 'ร้อยเอ็ด', 'name_en' => 'Roi Et', 'geography_id' => '3'],
	['id' => '34', 'jqvmap' => 'th-46', 'name_th' => 'กาฬสินธุ์', 'name_en' => 'Kalasin', 'geography_id' => '3'],
	['id' => '35', 'jqvmap' => 'th-47', 'name_th' => 'สกลนคร', 'name_en' => 'Sakon Nakhon', 'geography_id' => '3'],
	['id' => '36', 'jqvmap' => 'th-48', 'name_th' => 'นครพนม', 'name_en' => 'Nakhon Phanom', 'geography_id' => '3'],
	['id' => '37', 'jqvmap' => 'th-49', 'name_th' => 'มุกดาหาร', 'name_en' => 'Mukdahan', 'geography_id' => '3'],
	['id' => '38', 'jqvmap' => 'th-50', 'name_th' => 'เชียงใหม่', 'name_en' => 'Chiang Mai', 'geography_id' => '1'],
	['id' => '39', 'jqvmap' => 'th-51', 'name_th' => 'ลำพูน', 'name_en' => 'Lamphun', 'geography_id' => '1'],
	['id' => '40', 'jqvmap' => 'th-52', 'name_th' => 'ลำปาง', 'name_en' => 'Lampang', 'geography_id' => '1'],
	['id' => '41', 'jqvmap' => 'th-53', 'name_th' => 'อุตรดิตถ์', 'name_en' => 'Uttaradit', 'geography_id' => '1'],
	['id' => '42', 'jqvmap' => 'th-54', 'name_th' => 'แพร่', 'name_en' => 'Phrae', 'geography_id' => '1'],
	['id' => '43', 'jqvmap' => 'th-55', 'name_th' => 'น่าน', 'name_en' => 'Nan', 'geography_id' => '1'],
	['id' => '44', 'jqvmap' => 'th-56', 'name_th' => 'พะเยา', 'name_en' => 'Phayao', 'geography_id' => '1'],
	['id' => '45', 'jqvmap' => 'th-57', 'name_th' => 'เชียงราย', 'name_en' => 'Chiang Rai', 'geography_id' => '1'],
	['id' => '46', 'jqvmap' => 'th-58', 'name_th' => 'แม่ฮ่องสอน', 'name_en' => 'Mae Hong Son', 'geography_id' => '1'],
	['id' => '47', 'jqvmap' => 'th-60', 'name_th' => 'นครสวรรค์', 'name_en' => 'Nakhon Sawan', 'geography_id' => '2'],
	['id' => '48', 'jqvmap' => 'th-61', 'name_th' => 'อุทัยธานี', 'name_en' => 'Uthai Thani', 'geography_id' => '2'],
	['id' => '49', 'jqvmap' => 'th-62', 'name_th' => 'กำแพงเพชร', 'name_en' => 'Kamphaeng Phet', 'geography_id' => '2'],
	['id' => '50', 'jqvmap' => 'th-63', 'name_th' => 'ตาก', 'name_en' => 'Tak', 'geography_id' => '4'],
	['id' => '51', 'jqvmap' => 'th-64', 'name_th' => 'สุโขทัย', 'name_en' => 'Sukhothai', 'geography_id' => '2'],
	['id' => '52', 'jqvmap' => 'th-65', 'name_th' => 'พิษณุโลก', 'name_en' => 'Phitsanulok', 'geography_id' => '2'],
	['id' => '53', 'jqvmap' => 'th-66', 'name_th' => 'พิจิตร', 'name_en' => 'Phichit', 'geography_id' => '2'],
	['id' => '54', 'jqvmap' => 'th-67', 'name_th' => 'เพชรบูรณ์', 'name_en' => 'Phetchabun', 'geography_id' => '2'],
	['id' => '55', 'jqvmap' => 'th-70', 'name_th' => 'ราชบุรี', 'name_en' => 'Ratchaburi', 'geography_id' => '4'],
	['id' => '56', 'jqvmap' => 'th-71', 'name_th' => 'กาญจนบุรี', 'name_en' => 'Kanchanaburi', 'geography_id' => '4'],
	['id' => '57', 'jqvmap' => 'th-72', 'name_th' => 'สุพรรณบุรี', 'name_en' => 'Suphan Buri', 'geography_id' => '2'],
	['id' => '58', 'jqvmap' => 'th-73', 'name_th' => 'นครปฐม', 'name_en' => 'Nakhon Pathom', 'geography_id' => '2'],
	['id' => '59', 'jqvmap' => 'th-74', 'name_th' => 'สมุทรสาคร', 'name_en' => 'Samut Sakhon', 'geography_id' => '2'],
	['id' => '60', 'jqvmap' => 'th-75', 'name_th' => 'สมุทรสงคราม', 'name_en' => 'Samut Songkhram', 'geography_id' => '2'],
	['id' => '61', 'jqvmap' => 'th-76', 'name_th' => 'เพชรบุรี', 'name_en' => 'Phetchaburi', 'geography_id' => '4'],
	['id' => '62', 'jqvmap' => 'th-77', 'name_th' => 'ประจวบคีรีขันธ์', 'name_en' => 'Prachuap Khiri Khan', 'geography_id' => '4'],
	['id' => '63', 'jqvmap' => 'th-80', 'name_th' => 'นครศรีธรรมราช', 'name_en' => 'Nakhon Si Thammarat', 'geography_id' => '6'],
	['id' => '64', 'jqvmap' => 'th-81', 'name_th' => 'กระบี่', 'name_en' => 'Krabi', 'geography_id' => '6'],
	['id' => '65', 'jqvmap' => 'th-82', 'name_th' => 'พังงา', 'name_en' => 'Phangnga', 'geography_id' => '6'],
	['id' => '66', 'jqvmap' => 'th-83', 'name_th' => 'ภูเก็ต', 'name_en' => 'Phuket', 'geography_id' => '6'],
	['id' => '67', 'jqvmap' => 'th-84', 'name_th' => 'สุราษฎร์ธานี', 'name_en' => 'Surat Thani', 'geography_id' => '6'],
	['id' => '68', 'jqvmap' => 'th-85', 'name_th' => 'ระนอง', 'name_en' => 'Ranong', 'geography_id' => '6'],
	['id' => '69', 'jqvmap' => 'th-86', 'name_th' => 'ชุมพร', 'name_en' => 'Chumphon', 'geography_id' => '6'],
	['id' => '70', 'jqvmap' => 'th-90', 'name_th' => 'สงขลา', 'name_en' => 'Songkhla', 'geography_id' => '6'],
	['id' => '71', 'jqvmap' => 'th-91', 'name_th' => 'สตูล', 'name_en' => 'Satun', 'geography_id' => '6'],
	['id' => '72', 'jqvmap' => 'th-92', 'name_th' => 'ตรัง', 'name_en' => 'Trang', 'geography_id' => '6'],
	['id' => '73', 'jqvmap' => 'th-93', 'name_th' => 'พัทลุง', 'name_en' => 'Phatthalung', 'geography_id' => '6'],
	['id' => '74', 'jqvmap' => 'th-94', 'name_th' => 'ปัตตานี', 'name_en' => 'Pattani', 'geography_id' => '6'],
	['id' => '75', 'jqvmap' => 'th-95', 'name_th' => 'ยะลา', 'name_en' => 'Yala', 'geography_id' => '6'],
	['id' => '76', 'jqvmap' => 'th-96', 'name_th' => 'นราธิวาส', 'name_en' => 'Narathiwat', 'geography_id' => '6'],
	['id' => '77', 'jqvmap' => 'th-97', 'name_th' => 'บึงกาฬ', 'name_en' => 'buogkan', 'geography_id' => '3']
];

?> 

